### PR TITLE
ci: set it up

### PR DESCRIPTION
**Pull request by Thomaash**
Linting, testing, type checking and semantic releases.

Addresses #8.

### CODE REVIEW

**Comment by Thomaash** [comment]
@mojoaxel Also I need a permission again.

PS: vis-data is ready too but I don't have the permission to enable that one either.

**Comment by mojoaxel** [comment]
> Also I need a permission again.
PS: vis-data is ready too but I don't have the permission to enable that one either.

Done!

**Review by mojoaxel — APPROVED** [review]
LGTM

**Comment by Thomaash** [comment]
> > Also I need a permission again.
> > PS: vis-data is ready too but I don't have the permission to enable that one either.
> 
> Done!

Thanks.

**Pull request merged**
