### PR TITLE
TypeScript

### PR DESCRIPTION
**Pull request by Thomaash**
Hi, I rewrote vis-uuid into TypeScript. In case you're interested you can merge it (and I won't have to think of a name for it ☺). Everything is backwards compatible and works without problems in vis-charts.

It includes:
- New (tree shaking friendly) API, but the old one still works
- UMD and ESM builds (Rollup and Babel)
- Docs (TypeDoc), you have to enable GitHub Pages (docs on master branch) for this to work
- Linting (ESLint and Prettier)
- Better tests (from 2 to 19 cases, more detailed, better coverage)
- And a few more minor things

### CODE REVIEW

**Review by mojoaxel — APPROVED** [review]
A-M-A-Z-I-N-G!!
@Thomaash Thank you so much. Everythink look very good.
I needed to update babel-core in the vis-charts repository and everything works fine.

**Comment by Thomaash** [comment]
You're welcome.

**Comment by mojoaxel** [comment]
@Thomaash I'm really thankful for this. As you might seen I'm in the progress to split the vis.js library into separated packages that than could be maintained by different teams. So far I was not very successful because the gulp-based build process is quite messy.

I really want to encourage you to join me! Feel free to have a look at [vis-util](https://github.com/visjs/vis-util), it also could use some of your magic ;-)

**Comment by Thomaash** [comment]
How many packages do you want? Because I have some other modules in TS already (from visjs-community/visjs-network, the entire thing actually, but with 230 type errors at the moment). I could turn some parts of it into packages today or tomorrow (if everything goes smoothly, although it rarely does).

**Comment by mojoaxel** [comment]
> How many packages do you want?

I would really love to separate each chart type. Have a look at the new [website](https://visjs.github.io/www.visjs.org/). To be honest It is not important at this stage, that everything is in TypeScript, but It really needs a cleanup.

> from visjs-community/visjs-network

My main problem with the "visjs-community" repositories is that they just copied the project without the git history. I don't thing this is fair use! Also it is a one-man-show and he did not really care about the creator "almende" and the existing community.

I'm really not sure what the right think to do is at the moment...My main goal is to save the projects as a whole and create a new sustainable community.

**Comment by mojoaxel** [comment]
By the way: If you give me your npm.org user I'll add you ass collaborator for [vis-uuid](https://www.npmjs.com/package/vis-uuid) so that you can publish new versions. I consider this module yours from now on ;-)

**Comment by Thomaash** [comment]
I'm tom.vycital on npm.

**Comment by Thomaash** [comment]
I'll look at dataset and dataview. Maybe I could contribute this as a package this week.

**Comment by mojoaxel** [comment]
> I'll look at dataset and dataview. Maybe I could contribute this as a package this week.

That would be a very helpful!
The goal would be to take ne files from vis-charts, put them in their own repository and provide a build/transpile step for them.

As I said I would love to save the git history of each file but I guess it makes not much sense if it gets rewritten anyway :-|

**Comment by mojoaxel** [comment]
@Thomaash I'm current in the process to convert the build process to rollup. Network and timeline aready working. After this is done I can seperate everything much easier.

**Pull request merged**
